### ISSUE TITLE
found 6 vulnerabilities in this example

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/get-started-node#21]
~/tmp/IBM-Cloud/get-started-node$ npm install
added 142 packages from 168 contributors and audited 404 packages in 2.91s
found 6 vulnerabilities (3 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by rvennam** [comment]
Fixed with 27f36e06d2a050eccd4ed0237f4fc4719e98967b
