### ISSUE TITLE
Cloning a sample app Issue

### ISSUE THREAD

**Issue by bfalah** [IBM-Cloud/get-started-node#33]
Hi,
I tried to clone the sample app by running the following command as indicated in the lecture of unit 3
git clone https://github.com/IBM-Cloud/get-started-node
But I got the following error message:
fatal: could not create work tree dir 'get-started-node': Permission denied

Any help is much appreciated

**Comment by lidderupk** [comment]
I am guessing this problem was resolved? If so, let's close the issue. If not, can you please try again? I am able to clone.
